In [3]:
import numpy as np

In [ ]:
#Python list
python_list = [1, 2, 3, 4, 5]

#Numpy Array
numpy_array = np.array([1, 2, 3, 4, 5])

print("Pyton List", python_list)
print("Numpy Array", numpy_array)

print("Type of Python List:", type(python_list))
print("Type of Numpy Array:", type(numpy_array)) #ndarray - NDimensional Array

# KeY advantage : Vectorized operations (no loops needed)
# Adding 10 to each element
print("Python list (requires loops):", [x + 10 for x in python_list])
print("Numpy Array (vectorized):", numpy_array + 10) 

Pyton List [1, 2, 3, 4, 5]
Numpy Array [1 2 3 4 5]
Type of Python List: <class 'list'>
Type of Numpy Array: <class 'numpy.ndarray'>
Python list (requires loops): [11, 12, 13, 14, 15]
Numpy Array (vectorized): [11 12 13 14 15]


In [6]:
# Creating Numpy Arrays

#Method 1: From Python List 
arr1 = np.array([1, 2, 3, 4, 5])
print ("From list:", arr1)

#Method 2: Using np.arrange() - similar to range()
arr2 = np.arange(0, 10, 2)
print("Using range:", arr2)

#Method 3: Using np.linespace() - evenly spaced numbers
arr3 = np.linspace(0, 1, 5) # - start, stop, number of elements
print("Using linspace:", arr3)

#Method 4: Creating arrays of zero
zeros = np.zeros(5)
print("Zeros:", zeros)

#Method 5: Creating arrays of ones
ones = np.ones(5)
print("Ones:", ones)

#Method 6: Creating Arrays with specific values
full = np.full(5, 7) #shape, fill_values
print("Full (all 7s):", full)

#Method 7: Creating Arrays of identity Matrix
identity = np.eye(3)
print("Identity Matrix:\n", identity)

#Method 8: Random arrays
random_arr = np.random.rand(5)
print("Random(Uniform):", random_arr)

random_int = np.random.randint(1, 10, size = 5) # (low, high, size)
print("Random integers:", random_int)

From list: [1 2 3 4 5]
Using range: [0 2 4 6 8]
Using linspace: [0.   0.25 0.5  0.75 1.  ]
Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Full (all 7s): [7 7 7 7 7]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random(Uniform): [0.21363635 0.64329927 0.06087063 0.7039979  0.9818306 ]
Random integers: [1 5 8 8 7]


In [ ]:
# Multi Dimensional Arrays
## For 2D Array
matrix_2D = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array (Matrix):")
print(matrix_2D)
print(f"Shape of Matrix: {matrix_2D.shape}")
print(f"Number of Dimensions {matrix_2D.ndim}")
print(f"Sixe: {matrix_2D.size}")
print(f"Dta type: {matrix_2D.dtype}")


2D Array (Matrix):
[[1 2 3]
 [4 5 6]]
Shape of Matrix: (2, 3)
Number of Dimensions 2
Sixe: 6
Dta type: int64


In [9]:
## For 3D Array
matrix_3D = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])
print("2D Array (Matrix):")
print(matrix_3D)
print(f"Shape of Matrix: {matrix_3D.shape}")
print(f"Number of Dimensions {matrix_3D.ndim}")
print(f"Sixe: {matrix_3D.size}")
print(f"Dta type: {matrix_3D.dtype}")
print(f"Itemsize: {matrix_3D.itemsize} bytes") # Size of each elemet
print(f"nbytes: {matrix_3D.nbytes} bytes") #Total memory used
print(f" T (transpose): \n{matrix_3D.T}") #Transpose of the array

2D Array (Matrix):
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of Matrix: (2, 2, 3)
Number of Dimensions 3
Sixe: 12
Dta type: int64
Itemsize: 8 bytes
nbytes: 96 bytes
 T (transpose): 
[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]
